server:
  port: ${SERVER_PORT:8888}

  tomcat:
    accesslog:
      enabled: true
      file-date-format: .yyyy-MM-dd-HH-mm-ss
    basedir: log

  servlet:
    session:
      timeout: 86400s

spring:
  application:
    name: spring-boot-scaffold

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:spring-boot-scaffold}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:ALLURE_love921}
  #    url: jdbc:h2:./h2/db_test

  redis:
    host: localhost
    port: 6379
    password: ALLURE_love921

  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session

  servlet:
    multipart:
      enabled: true
      max-file-size: 512MB # 单个文件的最大上限
      max-request-size: 512MB # 单个请求的文件总大小上限

mybatis:
  configuration:
    cache-enabled: false # 关闭二级缓存
    local-cache-scope: statement # 一级缓存级别设置为statement
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true