package com.icuxika.scaffold.module.user.entity;

import javax.annotation.Generated;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_local_auth
 */
public class LocalAuth {
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9917698+08:00", comments = "Source field: t_local_auth.id")
    private Long id;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9917698+08:00", comments = "Source field: t_local_auth.username")
    private String username;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9917698+08:00", comments = "Source field: t_local_auth.password")
    private String password;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9917698+08:00", comments = "Source field: t_local_auth.phone")
    private String phone;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9917698+08:00", comments = "Source field: t_local_auth.id")
    public Long getId() {
        return id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9917698+08:00", comments = "Source field: t_local_auth.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9917698+08:00", comments = "Source field: t_local_auth.username")
    public String getUsername() {
        return username;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9917698+08:00", comments = "Source field: t_local_auth.username")
    public void setUsername(String username) {
        this.username = username;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9917698+08:00", comments = "Source field: t_local_auth.password")
    public String getPassword() {
        return password;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9917698+08:00", comments = "Source field: t_local_auth.password")
    public void setPassword(String password) {
        this.password = password;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9917698+08:00", comments = "Source field: t_local_auth.phone")
    public String getPhone() {
        return phone;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9927697+08:00", comments = "Source field: t_local_auth.phone")
    public void setPhone(String phone) {
        this.phone = phone;
    }
}