package com.icuxika.scaffold.module.user.entity;

import javax.annotation.Generated;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_third_auth
 */
public class ThirdAuth {
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9947691+08:00", comments = "Source field: t_third_auth.id")
    private Long id;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9947691+08:00", comments = "Source field: t_third_auth.open_id")
    private Long openId;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9947691+08:00", comments = "Source field: t_third_auth.type")
    private Integer type;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9947691+08:00", comments = "Source field: t_third_auth.id")
    public Long getId() {
        return id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9947691+08:00", comments = "Source field: t_third_auth.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9947691+08:00", comments = "Source field: t_third_auth.open_id")
    public Long getOpenId() {
        return openId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9947691+08:00", comments = "Source field: t_third_auth.open_id")
    public void setOpenId(Long openId) {
        this.openId = openId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9947691+08:00", comments = "Source field: t_third_auth.type")
    public Integer getType() {
        return type;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9947691+08:00", comments = "Source field: t_third_auth.type")
    public void setType(Integer type) {
        this.type = type;
    }
}