package com.icuxika.scaffold.module.user.entity;

import javax.annotation.Generated;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user_auth
 */
public class UserAuth {
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9887722+08:00", comments = "Source field: t_user_auth.id")
    private Long id;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9887722+08:00", comments = "Source field: t_user_auth.user_id")
    private Long userId;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9887722+08:00", comments = "Source field: t_user_auth.auth_id")
    private Long authId;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9887722+08:00", comments = "Source field: t_user_auth.type")
    private Integer type;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9887722+08:00", comments = "Source field: t_user_auth.id")
    public Long getId() {
        return id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9887722+08:00", comments = "Source field: t_user_auth.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9887722+08:00", comments = "Source field: t_user_auth.user_id")
    public Long getUserId() {
        return userId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9887722+08:00", comments = "Source field: t_user_auth.user_id")
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9887722+08:00", comments = "Source field: t_user_auth.auth_id")
    public Long getAuthId() {
        return authId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9887722+08:00", comments = "Source field: t_user_auth.auth_id")
    public void setAuthId(Long authId) {
        this.authId = authId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9887722+08:00", comments = "Source field: t_user_auth.type")
    public Integer getType() {
        return type;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2021-05-26T14:08:41.9887722+08:00", comments = "Source field: t_user_auth.type")
    public void setType(Integer type) {
        this.type = type;
    }
}